name: C Build

on:
  push:
  pull-request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Compilar programa
        run: gcc CartasSuperTrunfo.c -o programa
      
      - name: Executar programa
        run: ./programa